export const products = [
    {
        firstProductImage: '/images/img/1.webp',
        secondProductImage: '/images/img/1b.webp',
        discount: 50,
        sustenability: true,
        brand: "Levi's",
        model: 'RELAXED FIT TEE UNISEX',
        price: 29.99,
    },
    {
        firstProductImage: '/images/img/2.webp',
        secondProductImage: '/images/img/2b.webp',
        discount: 30,
        sustenability: false,
        brand: "Guess",
        model: 'ROSES TEE',
        price: 29.99,
    },
    {
        firstProductImage: '/images/img/3.webp',
        secondProductImage: '/images/img/3b.webp',
        discount: 30,
        sustenability: false,
        brand: "Come Zucchero Filato",
        model: 'VOGLIA DI COLORI PASTELLO',
        price: 184.99,
    },
    {
        firstProductImage: '/images/img/4.webp',
        secondProductImage: '/images/img/4b.webp',
        discount: 50,
        sustenability: true,
        brand: "Levi's",
        model: 'TEE UNISEX',
        price: 29.99,
    },
    {
        firstProductImage: '/images/img/5.webp',
        secondProductImage: '/images/img/5b.webp',
        discount: 0,
        sustenability: false,
        brand: "Maya Deluxe",
        model: 'STRIPE BODICE',
        price: 99.99,
    },
    {
        firstProductImage: '/images/img/6.webp',
        secondProductImage: '/images/img/6b.webp',
        discount: 0,
        sustenability: true,
        brand: "Esprit",
        model: 'MAGLIONE - BLACK',
        price: 29.99,
    },
]